### ISSUE TITLE
Duplicate lat/lngs

### ISSUE THREAD

**Issue by russbiggs** [russbiggs/spot-the-box-backend#1]
a quick run through in pandas shows we have about 61k points that are duplicates of one another.  

https://gist.github.com/russbiggs/94f6c6e32156f87329e39f1d516c8fdb

Some are just pairs of duplicates one is up to 14 points in the same lat/lng (i.e. OUTLET ID 2830200002 in Fayetteville NC). To resolve this we can add a jitter to the coordinates so the points don't stack on the map and users can distinguish between stacked points.  We'd want to apply the same jitter to already surveyed points as well given the outletID key.

**Comment by russbiggs** [comment]
@mikelmaron

**Comment by russbiggs** [comment]
closing as this will be solved in the front end

**Comment by mikelmaron** [comment]
sorry I haven't looked into this yet @russbiggs. there might be a bug on the api, since it should only be returning that latest point itself. however if the front end can solve this, we can go that way.

**Comment by russbiggs** [comment]
@mikel thats a different issue. This issue was for multiple points overlapping in the dataset.

**Comment by mikelmaron** [comment]
ah gotcha
